### PR TITLE
some improvements for this workflow

### PR DESCRIPTION
**Pull request by Geng-G-Razor**
1. Replace the {query} strict matching with the loose matching which starts from head;
2. Download all categories including 'happy' and 'dongers' which could not be downloaded before;
3. Download all emotions from most categories which's largest count was 30 before;
4. Forgiving my poor English.  ᕕ( ՞ ᗜ ՞ )ᕗ

### CODE REVIEW

**Comment by frdmn** [comment]
This looks awesome, buddy! 

Thanks a lot. I'll review tomorrow morning :+1:

PS: Your english is great!

**Comment by Geng-G-Razor** [comment]
Ok, good night !

**Comment by frdmn** [comment]
I just released an even more improved version 0.3.0

https://github.com/frdmn/alfred-dongers/releases/tag/0.3.0

Thanks again, @Geng-G-Razor

**Comment by Geng-G-Razor** [comment]
It's my pleasure.
Very Great improvements, Nice work.
But I still have some little questions.
1. Should I must download the .alfred-dongers.cache file manual? In my mac, I have to do so.
2. You didn't add the Fuzzy matching in this version, Yeah, it can result a little lag and it is not a ripe time to includue this feature. Just mention.

**Comment by frdmn** [comment]
Hey @Geng-G-Razor 

1. No actually, my intention was that no-one has to run the parser maually to get this workflow initially working. I'll take a look right now what's the actual problem right now. 
2. Good idea, care to create a new issue for that (as feature request)

**Comment by Geng-G-Razor** [comment]
Hey @frdmn 
1. I think the .alfred-dongers.cache file is not included in the Dongers.alfredworkflow, but it is in the source code zip.
2. I add Fuzzy matching in the wrapper.php in my PR, and as you have rebuilt your code , it can not work now......

**Comment by frdmn** [comment]
@Geng-G-Razor Ha! The issue was that is was a hidden file (prefixed with `.`), so whenever I exported my workflow out of Alfred to upload the release, Alfred secretly stripped the file before creating the package. 

I just renamed it to `alfred-dongers.cache` and it should be fixed now :)

---

What exactly do you mean with `fuzzy searching`? Because I can't really the implied code in your commit. Perhaps we are talking about two different things when we speak about `fuzzy searching`. :)

**Comment by Geng-G-Razor** [comment]
When I input ma , it can match with man, mad and magic, that's what i say fuzzy matching.

**Comment by frdmn** [comment]
@Geng-G-Razor Ah okay, because for me fuzzy search is more something like this:

- Searching for "maggic" (duplicate `g`, but the result "magic" still shows up.
- Searching for "shurpised" (`sh` instead of `s`), but "surprised" shows up.

Then you probably speak of this line:

` if (strpos($donger->category,strtolower($argv[1])) === 0) {`

I'll see if I can implement something like this again :)

**Comment by Geng-G-Razor** [comment]
Yeah, you have made it clear.

**Pull request merged**
