### PR TITLE
Fix the bug that can not download happy && donger categories

### PR DESCRIPTION
**Pull request by Geng-G-Razor**
I downloaded that alfred-workflow, and try to find some emotion like happy. However, i was suspicious to find that there were no result.
And after 3 hours' working, I , a front-end engineer fixed this bug.
Ennnn, there is still another little bug that only 30 items of run category can be downloaded. But, let me have a sleep now. It's too late.
May you have a nice day!

### CODE REVIEW

**Comment by frdmn** [comment]
Thanks for the PR. I'm a front-end dude as well! :hand: 

To be honest, I never really made use of this workflow and kind of abandoned it since I don't even have it installed at the moment. That being said, there could be a lot of changes on the http://dongerlist.com website since the original release of the workflow (one year ago). 

I'll review your changes later this week and see if the workflow still works like intented. One last request though: could you squash your three attempts into one single commit, please? I like to keep a clean git history :)

**Comment by Geng-G-Razor** [comment]
Ok, I will try. I am going to   push my new commit in about 12 hours and try to fix another bug.

**Comment by frdmn** [comment]
Awesome, thanks!

Von meinem iPhone gesendet

**Comment by Geng-G-Razor** [comment]
It seems that your server has shut down ʕ ಡ ﹏ ಡ ʔ. 
Maybe it's my fault that I requested frequently from your server.

**Comment by frdmn** [comment]
It's not my server, I don't run or maintain dongerslist.com at all. I just built a scraper for it using this workflow. I can access it from my end though:

```shell
❯  ~  curl -IL http://dongerlist.com/
HTTP/1.1 200 OK
...
```

**Comment by Geng-G-Razor** [comment]
Ok, got it.

**Comment by frdmn** [comment]
Closing this PR since it is obsolete (@Geng-G-Razor replaced it with a new one - #5).

**Pull request closed without merging**
